import { MessageCodes } from '@stechy1/diplomka-share';

const _MESSAGE_CODE_TRANSLATOR = {};

_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR] = 'CODE_ERROR';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_SUCCESS] = 'CODE_SUCCESS';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_EXPERIMENT_NOT_FOUND] =
  'CODE_ERROR_EXPERIMENT_NOT_FOUND';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_SUCCESS_EXPERIMENT_CREATED] =
  'CODE_SUCCESS_EXPERIMENT_CREATED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_EXPERIMENT_WAS_NOT_CREATED] =
  'CODE_ERROR_EXPERIMENT_WAS_NOT_CREATED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_SUCCESS_EXPERIMENT_UPDATED] =
  'CODE_SUCCESS_EXPERIMENT_UPDATED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_EXPERIMENT_WAS_NOT_UPDATED] =
  'CODE_ERROR_EXPERIMENT_WAS_NOT_UPDATED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_SUCCESS_EXPERIMENT_DELETED] =
  'CODE_SUCCESS_EXPERIMENT_DELETED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_EXPERIMENT_WAS_NOT_DELETED] =
  'CODE_ERROR_EXPERIMENT_WAS_NOT_DELETED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_EXPERIMENT_NOT_VALID] =
  'CODE_ERROR_EXPERIMENT_NOT_VALID';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_EXPERIMENT_ALREADY_EXISTS] =
  'CODE_ERROR_EXPERIMENT_ALREADY_EXISTS';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_EXPERIMENT_RESULT_NOT_FOUND] =
  'CODE_ERROR_EXPERIMENT_RESULT_NOT_FOUND';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_SUCCESS_EXPERIMENT_RESULT_CREATED] =
  'CODE_SUCCESS_EXPERIMENT_RESULT_CREATED';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_EXPERIMENT_RESULT_WAS_NOT_CREATED
] = 'CODE_ERROR_EXPERIMENT_RESULT_WAS_NOT_CREATED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_SUCCESS_EXPERIMENT_RESULT_UPDATED] =
  'CODE_SUCCESS_EXPERIMENT_RESULT_UPDATED';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_EXPERIMENT_RESULT_WAS_NOT_UPDATED
] = 'CODE_ERROR_EXPERIMENT_RESULT_WAS_NOT_UPDATED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_SUCCESS_EXPERIMENT_RESULT_DELETED] =
  'CODE_SUCCESS_EXPERIMENT_RESULT_DELETED';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_EXPERIMENT_RESULT_WAS_NOT_DELETED
] = 'CODE_ERROR_EXPERIMENT_RESULT_WAS_NOT_DELETED';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_EXPERIMENT_RESULT_DATA_NOT_FOUND
] = 'CODE_ERROR_EXPERIMENT_RESULT_DATA_NOT_FOUND';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_EXPERIMENT_RESULT_ALREADY_EXISTS
] = 'CODE_ERROR_EXPERIMENT_RESULT_ALREADY_EXISTS';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_EXPERIMENT_RESULT_NOT_VALID] =
  'CODE_ERROR_EXPERIMENT_RESULT_NOT_VALID';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_EXPERIMENT_RESULT_WAS_NOT_INITIALIZED
] = 'CODE_ERROR_EXPERIMENT_RESULT_WAS_NOT_INITIALIZED';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_EXPERIMENT_IS_NOT_INITIALIZED
] = 'CODE_ERROR_EXPERIMENT_IS_NOT_INITIALIZED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_SEQUENCE_NOT_FOUND] =
  'CODE_ERROR_SEQUENCE_NOT_FOUND';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_SUCCESS_SEQUENCE_CREATED] =
  'CODE_SUCCESS_SEQUENCE_CREATED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_SEQUENCE_NOT_CREATED] =
  'CODE_ERROR_SEQUENCE_NOT_CREATED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_SUCCESS_SEQUENCE_UPDATED] =
  'CODE_SUCCESS_SEQUENCE_UPDATED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_SEQUENCE_NOT_UPDATED] =
  'CODE_ERROR_SEQUENCE_NOT_UPDATED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_SUCCESS_SEQUENCE_DELETED] =
  'CODE_SUCCESS_SEQUENCE_DELETED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_SEQUENCE_NOT_DELETED] =
  'CODE_ERROR_SEQUENCE_NOT_DELETED';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_SEQUENCE_UNSUPORTED_EXPERIMENT
] = 'CODE_ERROR_SEQUENCE_UNSUPORTED_EXPERIMENT';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_SEQUENCE_EXPERIMENT_DO_NOT_SUPPORT_SEQUENCES
] = 'CODE_ERROR_SEQUENCE_EXPERIMENT_DO_NOT_SUPPORT_SEQUENCES';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_SEQUENCE_ALREADY_EXISTS] =
  'CODE_ERROR_SEQUENCE_ALREADY_EXISTS';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_SEQUENCE_NOT_VALID] =
  'CODE_ERROR_SEQUENCE_NOT_VALID';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_SEQUENCE_INVALID_SIZE] =
  'CODE_ERROR_SEQUENCE_INVALID_SIZE';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_SUCCESS_FILE_BROWSER_DIRECTORY_CREATED
] = 'CODE_SUCCESS_FILE_BROWSER_DIRECTORY_CREATED';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_SUCCESS_FILE_BROWSER_DIRECTORY_NOT_CREATED
] = 'CODE_SUCCESS_FILE_BROWSER_DIRECTORY_NOT_CREATED';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_SUCCESS_FILE_BROWSER_FILES_UPLOADED
] = 'CODE_SUCCESS_FILE_BROWSER_FILES_UPLOADED';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_FILE_BROWSER_FILES_NOT_UPLOADED
] = 'CODE_ERROR_FILE_BROWSER_FILES_NOT_UPLOADED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_SUCCESS_FILE_BROWSER_FILES_DELETED] =
  'CODE_SUCCESS_FILE_BROWSER_FILES_DELETED';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_FILE_BROWSER_FILES_NOT_DELETED
] = 'CODE_ERROR_FILE_BROWSER_FILES_NOT_DELETED';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_FILE_BROWSER_FILE_WAS_NOT_WRITTEN
] = 'CODE_ERROR_FILE_BROWSER_FILE_WAS_NOT_WRITTEN';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_FILE_BROWSER_FILE_ACCESS_RESTRICTED
] = 'CODE_ERROR_FILE_BROWSER_FILE_ACCESS_RESTRICTED';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_FILE_BROWSER_FILE_ALREADY_EXISTS
] = 'CODE_ERROR_FILE_BROWSER_FILE_ALREADY_EXISTS';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_FILE_BROWSER_FILE_NOT_FOUND] =
  'CODE_ERROR_FILE_BROWSER_FILE_NOT_FOUND';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_SUCCESS_LOW_LEVEL_PORT_OPPENED] =
  'CODE_SUCCESS_LOW_LEVEL_PORT_OPPENED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_LOW_LEVEL_PORT_NOT_OPPENED] =
  'CODE_ERROR_LOW_LEVEL_PORT_NOT_OPPENED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_SUCCESS_LOW_LEVEL_FIRMWARE_UPDATED] =
  'CODE_SUCCESS_LOW_LEVEL_FIRMWARE_UPDATED';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_LOW_LEVEL_FIRMWARE_NOT_UPDATED
] = 'CODE_ERROR_LOW_LEVEL_FIRMWARE_NOT_UPDATED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_LOW_LEVEL_PORT_NOT_OPEN] =
  'CODE_ERROR_LOW_LEVEL_PORT_NOT_OPEN';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_LOW_LEVEL_PORT_ALREADY_OPEN] =
  'CODE_ERROR_LOW_LEVEL_PORT_ALREADY_OPEN';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_LOW_LEVEL_PORT_UNABLE_TO_OPEN
] = 'CODE_ERROR_LOW_LEVEL_PORT_UNABLE_TO_OPEN';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_LOW_LEVEL_PORT_UNABLE_TO_CLOSE
] = 'CODE_ERROR_LOW_LEVEL_PORT_UNABLE_TO_CLOSE';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_SUCCESS_SETTINGS_UPDATED] =
  'CODE_SUCCESS_SETTINGS_UPDATED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_SETTINGS_NOT_UPDATED] =
  'CODE_ERROR_SETTINGS_NOT_UPDATED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_COMMANDS_INVALID_URL] =
  'CODE_ERROR_COMMANDS_INVALID_URL';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_COMMANDS_EXPERIMENT_UPLOAD] =
  'CODE_ERROR_COMMANDS_EXPERIMENT_UPLOAD';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_COMMANDS_EXPERIMENT_UPLOAD_NOT_CLEARED
] = 'CODE_ERROR_COMMANDS_EXPERIMENT_UPLOAD_NOT_CLEARED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_COMMANDS_EXPERIMENT_SETUP] =
  'CODE_ERROR_COMMANDS_EXPERIMENT_SETUP';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_COMMANDS_EXPERIMENT_SETUP_NOT_UPLOADED
] = 'CODE_ERROR_COMMANDS_EXPERIMENT_SETUP_NOT_UPLOADED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_COMMANDS_EXPERIMENT_RUN] =
  'CODE_ERROR_COMMANDS_EXPERIMENT_RUN';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_COMMANDS_EXPERIMENT_RUN_NOT_INITIALIZED
] = 'CODE_ERROR_COMMANDS_EXPERIMENT_RUN_NOT_INITIALIZED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_COMMANDS_EXPERIMENT_PAUSE] =
  'CODE_ERROR_COMMANDS_EXPERIMENT_PAUSE';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_COMMANDS_EXPERIMENT_PAUSE_NOT_STARTED
] = 'CODE_ERROR_COMMANDS_EXPERIMENT_PAUSE_NOT_STARTED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_COMMANDS_EXPERIMENT_FINISH] =
  'CODE_ERROR_COMMANDS_EXPERIMENT_FINISH';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_COMMANDS_EXPERIMENT_FINISH_NOT_RUNNING
] = 'CODE_ERROR_COMMANDS_EXPERIMENT_FINISH_NOT_RUNNING';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_COMMANDS_EXPERIMENT_CLEAR] =
  'CODE_ERROR_COMMANDS_EXPERIMENT_CLEAR';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_COMMANDS_STIMULATOR_STATE] =
  'CODE_ERROR_COMMANDS_STIMULATOR_STATE';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_STIMULATOR_FIRMWARE_NOT_UPDATED
] = 'CODE_ERROR_STIMULATOR_FIRMWARE_NOT_UPDATED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_STIMULATOR_UNKNOWN_ACTION] =
  'CODE_ERROR_STIMULATOR_UNKNOWN_ACTION';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_STIMULATOR_UNSUPPORTED_COMMAND
] = 'CODE_ERROR_STIMULATOR_UNSUPPORTED_COMMAND';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_STIMULATOR_NO_UPLOADED_EXPERIMENT
] = 'CODE_ERROR_STIMULATOR_NO_UPLOADED_EXPERIMENT';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_STIMULATOR_PLAYER_NOT_INITIALIZED
] = 'CODE_ERROR_STIMULATOR_PLAYER_NOT_INITIALIZED';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_STIMULATOR_ACTION_NOT_POSSIBLE
] = 'CODE_ERROR_STIMULATOR_ACTION_NOT_POSSIBLE';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_IPC_ALREADY_CONNECTED] =
  'CODE_ERROR_IPC_ALREADY_CONNECTED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_IPC_NOT_OPEN] =
  'CODE_ERROR_IPC_NOT_OPEN';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_AUTH_UNAUTHORIZED] =
  'CODE_ERROR_AUTH_UNAUTHORIZED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_SUCCESS_AUTH_LOGIN] =
  'CODE_SUCCESS_AUTH_LOGIN';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_AUTH_LOGIN_FAILED] =
  'CODE_ERROR_AUTH_LOGIN_FAILED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_SUCCESS_AUTH_TOKEN_REFRESH] =
  'CODE_SUCCESS_AUTH_TOKEN_REFRESH';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_AUTH_TOKEN_REFRESH_FAILED] =
  'CODE_ERROR_AUTH_TOKEN_REFRESH_FAILED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_AUTH_TOKEN_EXPIRED] =
  'CODE_ERROR_AUTH_TOKEN_EXPIRED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_AUTH_TOKEN_NOT_FOUND] =
  'CODE_ERROR_AUTH_TOKEN_NOT_FOUND';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_PLAYER_EXPERIMENT_RESULT_IS_NOT_INITIALIZED
] = 'CODE_ERROR_PLAYER_EXPERIMENT_RESULT_IS_NOT_INITIALIZED';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_PLAYER_ANOTHER_EXPERIMENT_RESULT_IS_INITIALIZED
] = 'CODE_ERROR_PLAYER_ANOTHER_EXPERIMENT_RESULT_IS_INITIALIZED';
_MESSAGE_CODE_TRANSLATOR[
  MessageCodes.CODE_ERROR_PLAYER_UNSUPPORTED_STOP_CONDITION
] = 'CODE_ERROR_PLAYER_UNSUPPORTED_STOP_CONDITION';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_USER_NOT_FOUND] =
  'CODE_ERROR_USER_NOT_FOUND';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_USER_ID_NOT_FOUND] =
  'CODE_ERROR_USER_ID_NOT_FOUND';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_USER_NOT_VALID] =
  'CODE_ERROR_USER_NOT_VALID';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_SUCCESS_USER_CREATED] =
  'CODE_SUCCESS_USER_CREATED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_USER_NOT_CREATED] =
  'CODE_ERROR_USER_NOT_CREATED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_USER_NOT_UPDATED] =
  'CODE_ERROR_USER_NOT_UPDATED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_USER_NOT_DELETED] =
  'CODE_ERROR_USER_NOT_DELETED';
_MESSAGE_CODE_TRANSLATOR[MessageCodes.CODE_ERROR_USER_NOT_REGISTRED] =
  'CODE_ERROR_USER_NOT_REGISTRED';

export const MESSAGE_CODE_TRANSLATOR = _MESSAGE_CODE_TRANSLATOR;
export const SERVER_MESSAGE_CODE_PREFIX = 'SERVER_MESSAGE_CODES.';
