const { getJestProjects } = require('@nrwl/jest');

module.exports = {
  projects: [
    ...getJestProjects(),
    '<rootDir>/apps/stimulator',
    '<rootDir>/libs/stim-lib-modal',
    '<rootDir>/libs/stim-lib-fab',
    '<rootDir>/libs/stim-lib-list-utils',
    '<rootDir>/libs/stim-lib-common',
    '<rootDir>/libs/stim-lib-ui',
    '<rootDir>/libs/stim-feature-about',
    '<rootDir>/libs/stim-feature-settings/feature',
    '<rootDir>/libs/stim-feature-settings/domain',
    '<rootDir>/libs/stim-feature-stimulator/domain',
    '<rootDir>/libs/stim-lib-store',
    '<rootDir>/libs/stim-lib-connection',
    '<rootDir>/libs/stim-feature-file-browser/domain',
    '<rootDir>/libs/stim-feature-file-browser/feature',
    '<rootDir>/libs/stim-feature-navigation/feature',
    '<rootDir>/libs/stim-feature-navigation/domain',
    '<rootDir>/libs/stim-feature-help/feature',
    '<rootDir>/libs/stim-feature-player/feature',
    '<rootDir>/libs/stim-feature-player/domain',
    '<rootDir>/libs/stim-feature-experiments/feature',
    '<rootDir>/libs/stim-feature-experiments/domain',
    '<rootDir>/libs/stim-feature-experiment-results/feature',
    '<rootDir>/libs/stim-feature-experiment-results/domain',
    '<rootDir>/libs/stim-feature-sequences/feature',
    '<rootDir>/libs/stim-feature-sequences/domain',
    '<rootDir>/libs/stim-feature-settings/popup',
    '<rootDir>/libs/stim-feature-settings/feature/console',
    '<rootDir>/libs/stim-feature-settings/feature/param-config',
    '<rootDir>/libs/stim-feature-settings/feature/service-state',
    '<rootDir>/libs/stim-feature-settings/feature/param-config/application',
    '<rootDir>/libs/stim-feature-settings/feature/param-config/experiments',
    '<rootDir>/libs/stim-feature-settings/feature/param-config/server',
    '<rootDir>/libs/stim-feature-users/feature',
    '<rootDir>/libs/stim-feature-users/domain',
    '<rootDir>/libs/stim-feature-auth/feature',
    '<rootDir>/libs/stim-feature-auth/domain',
    '<rootDir>/libs/stim-feature-stimulator/feature',
    '<rootDir>/libs/stim-lib-console/feature',
    '<rootDir>/libs/stim-lib-console/domain',
  ],
};
