# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: build

on: [push]

jobs:
  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@main
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: Install dependencies
      run: npm install
#    - name: Lint
#      run: npm run lint
    - name: Check translations
      run: npm run check-translations
#    - name: Check unused selectors
#      run: npm run check-unused-selectors
    - name: Build
      run: npm run release
#    - name: Test
#      run: npm run test
#    - name: Merge code coverage
#      run: npm run merge-coverage
#    - name: Coveralls
#      uses: coverallsapp/github-action@master
#      with:
#        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build doc
      run: npm run doc
    - name: Deploy to github pages
      uses: JamesIves/github-pages-deploy-action@4.2.1
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: documentation # The folder the action should deploy.
        clean: true # Automatically remove deleted files from the deploy branch
